import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { getDatabase } from "../../db/database.js";
import * as reportRepo from "../../db/report.repo.js";
import * as portfolioRepo from "../../db/portfolio.repo.js";
import { PortfolioReportService } from "../portfolio-report.js";
import type { LlmService } from "../llm.js";
import type { PortfolioService } from "../portfolio.js";
import type { PortfolioItem, FinancialPortfolioData } from "../../../types/portfolio.js";

describe("Portfolio Report Prompt Persistence", () => {
  const testPortfolioId = "test-portfolio-prompt-123";

  beforeEach(() => {
    const db = getDatabase();
    db.run("DELETE FROM reports WHERE portfolioId = ?", [testPortfolioId]);
    db.run("DELETE FROM portfolios WHERE id = ?", [testPortfolioId]);
    db.run(
      "INSERT OR REPLACE INTO portfolios (id, name, baseCurrency) VALUES (?, ?, ?)",
      [testPortfolioId, "Prompt Test Portfolio", "EUR"],
    );
  });

  afterEach(() => {
    const db = getDatabase();
    db.run("DELETE FROM reports WHERE portfolioId = ?", [testPortfolioId]);
    db.run("DELETE FROM portfolios WHERE id = ?", [testPortfolioId]);
  });

  it("reportRepo.upsert saves and retrieves the prompt", () => {
    const testPrompt = "### System Prompt\nYou are an analyst.\n\n### User Prompt\nAnalyze the portfolio.";
    const report = reportRepo.upsert({
      id: "report-test-1",
      portfolioId: testPortfolioId,
      period: "Sep 1 - Sep 7, 2026",
      weekStartDate: "2026-09-01",
      weekEndDate: "2026-09-07",
      weekKey: "2026-w36",
      title: "Test Report",
      summary: "Test Summary",
      content: "Detailed markdown analysis",
      prompt: testPrompt,
      metrics: {
        totalPortfolioValue: 50000,
        cashBalance: 10000,
        baseCurrency: "EUR",
        holdingsCount: 3,
      },
      model: "test-model",
      provider: "ollama",
    });

    expect(report).toBeDefined();
    expect(report.prompt).toBe(testPrompt);

    const fetched = reportRepo.findById("report-test-1");
    expect(fetched).not.toBeNull();
    expect(fetched!.prompt).toBe(testPrompt);

    const list = reportRepo.findByPortfolio(testPortfolioId);
    expect(list.length).toBe(1);
    expect(list[0]!.prompt).toBe(testPrompt);
  });

  it("PortfolioReportService.generateReport stores full prompt with system and user sections", async () => {
    let capturedPrompt: string | undefined;

    const mockLlmService = {
      chat: async (messages: { role: string; content: string }[]) => {
        const sysMsg = messages.find((m) => m.role === "system")?.content;
        const userMsg = messages.find((m) => m.role === "user")?.content;
        capturedPrompt = `### System Prompt\n${sysMsg}\n\n### User Prompt\n${userMsg}`;
        return "Tactical report generated by mock LLM";
      },
    } as unknown as LlmService;

    const mockPortfolioData: FinancialPortfolioData = {
      summary: {
        totalValue: 25000,
        totalCost: 20000,
        totalGainLossDollar: 5000,
        totalGainLossPercent: 25,
        dayGainLossDollar: 200,
        dayGainLossPercent: 0.8,
        totalGainSinceStartDollar: 5000,
        totalGainSinceStartPercent: 25,
        totalCashInjected: 20000,
        cashBalance: 5000,
        totalPortfolioValue: 30000,
        realizedPnL: 0,
        totalDividends: 0,
        totalInterest: 0,
        totalFees: 0,
        totalTaxes: 0,
        stockWeightPercent: 80,
        etfWeightPercent: 0,
        cryptoWeightPercent: 0,
        cashWeightPercent: 20,
        baseCurrency: "EUR",
        lastUpdated: new Date().toISOString(),
      },
      holdings: [
        {
          symbol: "SAP",
          name: "SAP SE",
          assetType: "Stock",
          shares: 50,
          buyPrice: 150,
          currentPrice: 180,
          previousClose: 178,
          totalCost: 7500,
          currentValue: 9000,
          dayChangeDollar: 100,
          dayChangePercent: 1.12,
          totalGainLossDollar: 1500,
          totalGainLossPercent: 20,
          weightPercent: 30,
          currency: "EUR",
          sma50: 170,
          sma200: 160,
          rsi: 55,
        },
      ],
      chartHistory: [],
      individualCharts: {},
    };

    const mockPortfolioService = {
      getPortfolioData: async () => mockPortfolioData,
    } as unknown as PortfolioService;

    const service = new PortfolioReportService(mockLlmService, mockPortfolioService);

    const portfolio: PortfolioItem = {
      id: testPortfolioId,
      name: "Prompt Test Portfolio",
      baseCurrency: "EUR",
    };

    const result = await service.generateReport(portfolio, {
      provider: "ollama",
      model: "llama3.2:latest",
      portfolioData: mockPortfolioData,
    });

    expect(result.prompt).toBeDefined();
    expect(result.prompt).toContain("### System Prompt");
    expect(result.prompt).toContain("### User Prompt");
    expect(result.prompt).toContain("SAP");
    expect(result.prompt).toContain("Prompt Test Portfolio");

    // Also verify getReports includes the prompt
    const { reports } = service.getReports(testPortfolioId);
    expect(reports.length).toBe(1);
    expect(reports[0]!.prompt).toBe(result.prompt);
  });
});
