// GENERATED by scripts/build-metrics.ts from src/shared/metric-abi.ts. Do not edit.
//
// Guest SDK for Portfolio metric modules (ABI v1).
// Input is a binary payload built by the host from the scopes the metric was
// granted. Output is a small JSON document built by `Result`. See
// extras/metrics/README.md for the contract.

export const ABI_VERSION: i32 = 1;

const MAGIC: u32 = 1413827920;
const HEADER_BYTES: usize = 32;

/** Required export: tells the host which ABI this module targets. */
export function metric_abi_version(): i32 {
  return ABI_VERSION;
}

/** Required export: the host writes the input payload into this allocation. */
export function metric_alloc(size: i32): i32 {
  return <i32>heap.alloc(<usize>size);
}

// ── Input ────────────────────────────────────────────────────────────────────

class Payload {
  base: usize;
  len: usize;

  constructor(ptr: i32, len: i32) {
    this.base = <usize>ptr;
    this.len = <usize>len;
    if (this.len < HEADER_BYTES) throw new Error("payload too small");
    if (load<u32>(this.base) != MAGIC) throw new Error("payload magic mismatch");
    if (load<u32>(this.base + 4) != <u32>ABI_VERSION) throw new Error("payload abi mismatch");
  }

  /** Offset of a block by header slot (3 = summary, 4 = holdings, 5 = transactions, 6 = history). */
  blockOffset(slot: i32): usize {
    const off = <usize>load<u32>(this.base + <usize>(slot << 2));
    if (off != 0 && off + 8 > this.len) throw new Error("payload block out of range");
    return off;
  }

  str(offset: u32, length: u32): string {
    if (<usize>offset + <usize>length > this.len) throw new Error("payload string out of range");
    return String.UTF8.decodeUnsafe(this.base + <usize>offset, <usize>length);
  }
}

/** Aggregate figures of the portfolio (scope `portfolio.summary`). */
export class Summary {
  private base: usize = 0;
  private count: i32 = 0;
  /** True when the host granted the summary scope. */
  readonly present: bool;

  constructor(ptr: i32, len: i32) {
    const p = new Payload(ptr, len);
    const off = p.blockOffset(3);
    this.present = off != 0;
    if (this.present) {
      this.count = <i32>load<u32>(p.base + off);
      this.base = p.base + off + 8;
    }
  }

  private field(i: i32): f64 {
    return i < this.count ? load<f64>(this.base + (<usize>i << 3)) : 0.0;
  }

  get totalValue(): f64 { return this.field(0); }
  get totalCost(): f64 { return this.field(1); }
  get totalGainLossDollar(): f64 { return this.field(2); }
  get totalGainLossPercent(): f64 { return this.field(3); }
  get dayGainLossDollar(): f64 { return this.field(4); }
  get dayGainLossPercent(): f64 { return this.field(5); }
  get totalGainSinceStartDollar(): f64 { return this.field(6); }
  get totalGainSinceStartPercent(): f64 { return this.field(7); }
  get totalCashInjected(): f64 { return this.field(8); }
  get totalCashWithdrawn(): f64 { return this.field(9); }
  get cashBalance(): f64 { return this.field(10); }
  get totalPortfolioValue(): f64 { return this.field(11); }
  get realizedPnL(): f64 { return this.field(12); }
  get totalDividends(): f64 { return this.field(13); }
  get totalInterest(): f64 { return this.field(14); }
  get totalFees(): f64 { return this.field(15); }
  get totalTaxes(): f64 { return this.field(16); }
  get stockWeightPercent(): f64 { return this.field(17); }
  get etfWeightPercent(): f64 { return this.field(18); }
  get cryptoWeightPercent(): f64 { return this.field(19); }
  get otherWeightPercent(): f64 { return this.field(20); }
  get cashWeightPercent(): f64 { return this.field(21); }
}

abstract class RecordList {
  protected payload: Payload;
  protected base: usize = 0;
  protected fieldCount: i32 = 0;
  protected recordBytes: usize = 0;
  /** Number of records. Zero when the scope was not granted. */
  readonly count: i32;
  /** True when the host granted the scope. */
  readonly present: bool;

  constructor(ptr: i32, len: i32, slot: i32, prefixBytes: usize) {
    this.payload = new Payload(ptr, len);
    const off = this.payload.blockOffset(slot);
    this.present = off != 0;
    let count = 0;
    if (this.present) {
      count = <i32>load<u32>(this.payload.base + off);
      this.fieldCount = <i32>load<u32>(this.payload.base + off + 4);
      this.base = this.payload.base + off + 8;
      this.recordBytes = prefixBytes + (<usize>this.fieldCount << 3);
      if (this.base + <usize>count * this.recordBytes > this.payload.base + this.payload.len) {
        throw new Error("payload records out of range");
      }
    }
    this.count = count;
  }

  protected recordPtr(i: i32): usize {
    if (i < 0 || i >= this.count) throw new Error("record index out of range");
    return this.base + <usize>i * this.recordBytes;
  }
}

export enum AssetType {
  Other = 0,
  Stock = 1,
  ETF = 2,
  MutualFund = 3,
  Crypto = 4,
  Cash = 5,
}

/** One open position (scope `portfolio.holdings`). */
export class Holding {
  constructor(private payload: Payload, private ptr: usize, private fieldCount: i32) {}

  get symbol(): string { return this.payload.str(load<u32>(this.ptr), load<u32>(this.ptr + 4)); }
  get assetType(): AssetType { return <AssetType>load<u32>(this.ptr + 8); }

  private field(i: i32): f64 {
    return i < this.fieldCount ? load<f64>(this.ptr + 16 + (<usize>i << 3)) : 0.0;
  }

  get shares(): f64 { return this.field(0); }
  get buyPrice(): f64 { return this.field(1); }
  get currentPrice(): f64 { return this.field(2); }
  get previousClose(): f64 { return this.field(3); }
  get totalCost(): f64 { return this.field(4); }
  get currentValue(): f64 { return this.field(5); }
  get dayChangeDollar(): f64 { return this.field(6); }
  get dayChangePercent(): f64 { return this.field(7); }
  get totalGainLossDollar(): f64 { return this.field(8); }
  get totalGainLossPercent(): f64 { return this.field(9); }
  get weightPercent(): f64 { return this.field(10); }
  get fiftyTwoWeekHigh(): f64 { return this.field(11); }
  get fiftyTwoWeekLow(): f64 { return this.field(12); }
  get sma50(): f64 { return this.field(13); }
  get sma200(): f64 { return this.field(14); }
  get rsi(): f64 { return this.field(15); }
}

export class Holdings extends RecordList {
  constructor(ptr: i32, len: i32) { super(ptr, len, 4, 16); }
  at(i: i32): Holding { return new Holding(this.payload, this.recordPtr(i), this.fieldCount); }
}

export enum TransactionKind {
  Other = 0,
  Buy = 1,
  Sell = 2,
  Dividend = 3,
  Interest = 4,
  Deposit = 5,
  Withdrawal = 6,
}

/** One ledger entry (scope `portfolio.transactions`). */
export class Transaction {
  constructor(private payload: Payload, private ptr: usize, private fieldCount: i32) {}

  get symbol(): string { return this.payload.str(load<u32>(this.ptr), load<u32>(this.ptr + 4)); }
  /** Raw broker type string, for example BUY or DIVIDEND. */
  get type(): string { return this.payload.str(load<u32>(this.ptr + 8), load<u32>(this.ptr + 12)); }
  get kind(): TransactionKind { return <TransactionKind>load<u32>(this.ptr + 16); }

  private field(i: i32): f64 {
    return i < this.fieldCount ? load<f64>(this.ptr + 24 + (<usize>i << 3)) : 0.0;
  }

  get timestamp(): f64 { return this.field(0); }
  get shares(): f64 { return this.field(1); }
  get price(): f64 { return this.field(2); }
  get amount(): f64 { return this.field(3); }
  get fee(): f64 { return this.field(4); }
  get tax(): f64 { return this.field(5); }
}

export class Transactions extends RecordList {
  constructor(ptr: i32, len: i32) { super(ptr, len, 5, 24); }
  at(i: i32): Transaction { return new Transaction(this.payload, this.recordPtr(i), this.fieldCount); }
}

/** One point of the equity curve (scope `portfolio.history`). */
export class HistoryPoint {
  constructor(private ptr: usize, private fieldCount: i32) {}

  private field(i: i32): f64 {
    return i < this.fieldCount ? load<f64>(this.ptr + (<usize>i << 3)) : 0.0;
  }

  get timestamp(): f64 { return this.field(0); }
  get totalValue(): f64 { return this.field(1); }
  get totalCost(): f64 { return this.field(2); }
  get totalGainLoss(): f64 { return this.field(3); }
  get cashBalance(): f64 { return this.field(4); }
  get totalPortfolioValue(): f64 { return this.field(5); }
}

export class History extends RecordList {
  constructor(ptr: i32, len: i32) { super(ptr, len, 6, 0); }
  at(i: i32): HistoryPoint { return new HistoryPoint(this.recordPtr(i), this.fieldCount); }
}

// ── Output ───────────────────────────────────────────────────────────────────

export enum Format {
  Currency = 0,
  Percent = 1,
  Number = 2,
  None = 3,
}

export enum Sign {
  Auto = 0,
  Always = 1,
  Never = 2,
}

const FORMAT_NAMES: string[] = ["currency", "percent", "number", "none"];
const SIGN_NAMES: string[] = ["auto", "always", "never"];

function jsonNumber(v: f64): string {
  return isFinite(v) ? v.toString() : "null";
}

function jsonString(s: string): string {
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c == 0x22) out += '\\"';
    else if (c == 0x5c) out += "\\\\";
    else if (c == 0x0a) out += "\\n";
    else if (c == 0x0d) out += "\\r";
    else if (c == 0x09) out += "\\t";
    else if (c < 0x20) out += "\\u00" + (c < 16 ? "0" : "") + c.toString(16);
    else out += String.fromCharCode(c);
  }
  return out + '"';
}

function amountJson(amount: f64, format: Format, sign: Sign): string {
  return '{"amount":' + jsonNumber(amount) + ',"format":"' + FORMAT_NAMES[<i32>format] + '","sign":"' + SIGN_NAMES[<i32>sign] + '"}';
}

/**
 * Builds the result document. Call `value()` once, add sub-line parts with
 * `text()` and `amount()` in display order, pick a color, then `finish()`.
 */
export class Result {
  private valueJson: string = "";
  private subParts: string[] = [];
  private sentiment: string = "";

  /** Main figure of the card. */
  value(amount: f64, format: Format, sign: Sign = Sign.Auto): Result {
    this.valueJson = amountJson(amount, format, sign);
    return this;
  }

  /** Literal text in the sub-line. */
  text(text: string): Result {
    this.subParts.push('{"text":' + jsonString(text) + "}");
    return this;
  }

  /** Formatted number in the sub-line. */
  amount(amount: f64, format: Format, sign: Sign = Sign.Auto): Result {
    this.subParts.push(amountJson(amount, format, sign));
    return this;
  }

  /** Color the value by the sign of the main figure. */
  auto(): Result { this.sentiment = "auto"; return this; }
  positive(): Result { this.sentiment = "positive"; return this; }
  negative(): Result { this.sentiment = "negative"; return this; }
  /** Muted color, for costs and informational figures. */
  neutral(): Result { this.sentiment = "neutral"; return this; }

  toJSON(): string {
    if (this.valueJson.length == 0) throw new Error("Result.value() was not called");
    let json = '{"value":' + this.valueJson;
    if (this.subParts.length > 0) json += ',"sub":[' + this.subParts.join(",") + "]";
    if (this.sentiment.length > 0) json += ',"sentiment":"' + this.sentiment + '"';
    return json + "}";
  }

  /** Encode the document and return the pointer the host expects: [u32 length][utf8 bytes]. */
  finish(): i32 {
    return emit(this.toJSON());
  }
}

/** Return any string to the host in the ABI result layout. */
export function emit(json: string): i32 {
  const buf = String.UTF8.encode(json);
  const n = <usize>buf.byteLength;
  const out = heap.alloc(4 + n);
  store<u32>(out, <u32>n);
  memory.copy(out + 4, changetype<usize>(buf), n);
  return <i32>out;
}
