/**
 * Build the metric modules in extras/metrics.
 *
 * 1. Generate the AssemblyScript SDK (extras/metrics/_sdk/portfolio.ts) from
 *    the ABI tables in src/shared/metric-abi.ts, so guest accessors and the
 *    host encoder share one definition.
 * 2. Validate repository.yml and every manifest.yml.
 * 3. Compile each metric with asc into build/metrics/<id>.wasm (skipped when
 *    the output is newer than its inputs; pass --force to rebuild).
 * 4. Emit src/bun/services/metrics/builtin-modules.generated.ts with the
 *    module bytes (base64), SHA-256, size, and manifest of every bundled
 *    metric, plus the repository listing.
 *
 * Usage: bun run scripts/build-metrics.ts [--force] [--check]
 *   --check  validate and compile, but do not write the generated SDK or
 *            the bundle; fails when the committed SDK is stale (CI).
 */

import asc from "assemblyscript/asc";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import {
  HISTORY_FIELDS,
  HOLDING_ASSET_TYPES,
  HOLDING_FIELDS,
  HOLDING_RECORD_PREFIX_BYTES,
  METRIC_ABI_VERSION,
  METRIC_PAYLOAD_MAGIC,
  MIN_METRIC_MEMORY_PAGES,
  MAX_METRIC_MEMORY_PAGES,
  PAYLOAD_HEADER_BYTES,
  SUMMARY_FIELDS,
  TRANSACTION_FIELDS,
  TRANSACTION_KINDS,
  TRANSACTION_RECORD_PREFIX_BYTES,
} from "../src/shared/metric-abi.ts";
import { validateMetricManifest, type MetricManifest } from "../src/shared/metric-manifest.ts";
import { isMetricId } from "../src/shared/metrics.ts";

const ROOT = resolve(import.meta.dir, "..");
const METRICS_DIR = join(ROOT, "extras", "metrics");
const SDK_PATH = join(METRICS_DIR, "_sdk", "portfolio.ts");
const OUT_DIR = join(ROOT, "build", "metrics");
const GENERATED_PATH = join(ROOT, "src", "bun", "services", "metrics", "builtin-modules.generated.ts");

const force = process.argv.includes("--force");
const checkOnly = process.argv.includes("--check");

interface RepositoryEntry {
  id: string;
  path: string;
  bundled: boolean;
}

// ── SDK generation ────────────────────────────────────────────────────────────

function pascal(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function fieldGetters(fields: readonly string[], indent: string): string {
  return fields.map((name, i) => `${indent}get ${name}(): f64 { return this.field(${i}); }`).join("\n");
}

function enumBlock(name: string, values: readonly string[]): string {
  return `export enum ${name} {\n${values.map((v, i) => `  ${v} = ${i},`).join("\n")}\n}`;
}

function generateSdk(): string {
  return `// GENERATED by scripts/build-metrics.ts from src/shared/metric-abi.ts. Do not edit.
//
// Guest SDK for Portfolio metric modules (ABI v${METRIC_ABI_VERSION}).
// Input is a binary payload built by the host from the scopes the metric was
// granted. Output is a small JSON document built by \`Result\`. See
// extras/metrics/README.md for the contract.

export const ABI_VERSION: i32 = ${METRIC_ABI_VERSION};

const MAGIC: u32 = ${METRIC_PAYLOAD_MAGIC};
const HEADER_BYTES: usize = ${PAYLOAD_HEADER_BYTES};

/** Required export: tells the host which ABI this module targets. */
export function metric_abi_version(): i32 {
  return ABI_VERSION;
}

/** Required export: the host writes the input payload into this allocation. */
export function metric_alloc(size: i32): i32 {
  return <i32>heap.alloc(<usize>size);
}

// ── Input ────────────────────────────────────────────────────────────────────

class Payload {
  base: usize;
  len: usize;

  constructor(ptr: i32, len: i32) {
    this.base = <usize>ptr;
    this.len = <usize>len;
    if (this.len < HEADER_BYTES) throw new Error("payload too small");
    if (load<u32>(this.base) != MAGIC) throw new Error("payload magic mismatch");
    if (load<u32>(this.base + 4) != <u32>ABI_VERSION) throw new Error("payload abi mismatch");
  }

  /** Offset of a block by header slot (3 = summary, 4 = holdings, 5 = transactions, 6 = history). */
  blockOffset(slot: i32): usize {
    const off = <usize>load<u32>(this.base + <usize>(slot << 2));
    if (off != 0 && off + 8 > this.len) throw new Error("payload block out of range");
    return off;
  }

  str(offset: u32, length: u32): string {
    if (<usize>offset + <usize>length > this.len) throw new Error("payload string out of range");
    return String.UTF8.decodeUnsafe(this.base + <usize>offset, <usize>length);
  }
}

/** Aggregate figures of the portfolio (scope \`portfolio.summary\`). */
export class Summary {
  private base: usize = 0;
  private count: i32 = 0;
  /** True when the host granted the summary scope. */
  readonly present: bool;

  constructor(ptr: i32, len: i32) {
    const p = new Payload(ptr, len);
    const off = p.blockOffset(3);
    this.present = off != 0;
    if (this.present) {
      this.count = <i32>load<u32>(p.base + off);
      this.base = p.base + off + 8;
    }
  }

  private field(i: i32): f64 {
    return i < this.count ? load<f64>(this.base + (<usize>i << 3)) : 0.0;
  }

${fieldGetters(SUMMARY_FIELDS, "  ")}
}

abstract class RecordList {
  protected payload: Payload;
  protected base: usize = 0;
  protected fieldCount: i32 = 0;
  protected recordBytes: usize = 0;
  /** Number of records. Zero when the scope was not granted. */
  readonly count: i32;
  /** True when the host granted the scope. */
  readonly present: bool;

  constructor(ptr: i32, len: i32, slot: i32, prefixBytes: usize) {
    this.payload = new Payload(ptr, len);
    const off = this.payload.blockOffset(slot);
    this.present = off != 0;
    let count = 0;
    if (this.present) {
      count = <i32>load<u32>(this.payload.base + off);
      this.fieldCount = <i32>load<u32>(this.payload.base + off + 4);
      this.base = this.payload.base + off + 8;
      this.recordBytes = prefixBytes + (<usize>this.fieldCount << 3);
      if (this.base + <usize>count * this.recordBytes > this.payload.base + this.payload.len) {
        throw new Error("payload records out of range");
      }
    }
    this.count = count;
  }

  protected recordPtr(i: i32): usize {
    if (i < 0 || i >= this.count) throw new Error("record index out of range");
    return this.base + <usize>i * this.recordBytes;
  }
}

${enumBlock("AssetType", HOLDING_ASSET_TYPES)}

/** One open position (scope \`portfolio.holdings\`). */
export class Holding {
  constructor(private payload: Payload, private ptr: usize, private fieldCount: i32) {}

  get symbol(): string { return this.payload.str(load<u32>(this.ptr), load<u32>(this.ptr + 4)); }
  get assetType(): AssetType { return <AssetType>load<u32>(this.ptr + 8); }

  private field(i: i32): f64 {
    return i < this.fieldCount ? load<f64>(this.ptr + ${HOLDING_RECORD_PREFIX_BYTES} + (<usize>i << 3)) : 0.0;
  }

${fieldGetters(HOLDING_FIELDS, "  ")}
}

export class Holdings extends RecordList {
  constructor(ptr: i32, len: i32) { super(ptr, len, 4, ${HOLDING_RECORD_PREFIX_BYTES}); }
  at(i: i32): Holding { return new Holding(this.payload, this.recordPtr(i), this.fieldCount); }
}

${enumBlock("TransactionKind", TRANSACTION_KINDS)}

/** One ledger entry (scope \`portfolio.transactions\`). */
export class Transaction {
  constructor(private payload: Payload, private ptr: usize, private fieldCount: i32) {}

  get symbol(): string { return this.payload.str(load<u32>(this.ptr), load<u32>(this.ptr + 4)); }
  /** Raw broker type string, for example BUY or DIVIDEND. */
  get type(): string { return this.payload.str(load<u32>(this.ptr + 8), load<u32>(this.ptr + 12)); }
  get kind(): TransactionKind { return <TransactionKind>load<u32>(this.ptr + 16); }

  private field(i: i32): f64 {
    return i < this.fieldCount ? load<f64>(this.ptr + ${TRANSACTION_RECORD_PREFIX_BYTES} + (<usize>i << 3)) : 0.0;
  }

${fieldGetters(TRANSACTION_FIELDS, "  ")}
}

export class Transactions extends RecordList {
  constructor(ptr: i32, len: i32) { super(ptr, len, 5, ${TRANSACTION_RECORD_PREFIX_BYTES}); }
  at(i: i32): Transaction { return new Transaction(this.payload, this.recordPtr(i), this.fieldCount); }
}

/** One point of the equity curve (scope \`portfolio.history\`). */
export class HistoryPoint {
  constructor(private ptr: usize, private fieldCount: i32) {}

  private field(i: i32): f64 {
    return i < this.fieldCount ? load<f64>(this.ptr + (<usize>i << 3)) : 0.0;
  }

${fieldGetters(HISTORY_FIELDS, "  ")}
}

export class History extends RecordList {
  constructor(ptr: i32, len: i32) { super(ptr, len, 6, 0); }
  at(i: i32): HistoryPoint { return new HistoryPoint(this.recordPtr(i), this.fieldCount); }
}

// ── Output ───────────────────────────────────────────────────────────────────

export enum Format {
  Currency = 0,
  Percent = 1,
  Number = 2,
  None = 3,
}

export enum Sign {
  Auto = 0,
  Always = 1,
  Never = 2,
}

const FORMAT_NAMES: string[] = ["currency", "percent", "number", "none"];
const SIGN_NAMES: string[] = ["auto", "always", "never"];

function jsonNumber(v: f64): string {
  return isFinite(v) ? v.toString() : "null";
}

function jsonString(s: string): string {
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c == 0x22) out += '\\\\"';
    else if (c == 0x5c) out += "\\\\\\\\";
    else if (c == 0x0a) out += "\\\\n";
    else if (c == 0x0d) out += "\\\\r";
    else if (c == 0x09) out += "\\\\t";
    else if (c < 0x20) out += "\\\\u00" + (c < 16 ? "0" : "") + c.toString(16);
    else out += String.fromCharCode(c);
  }
  return out + '"';
}

function amountJson(amount: f64, format: Format, sign: Sign): string {
  return '{"amount":' + jsonNumber(amount) + ',"format":"' + FORMAT_NAMES[<i32>format] + '","sign":"' + SIGN_NAMES[<i32>sign] + '"}';
}

/**
 * Builds the result document. Call \`value()\` once, add sub-line parts with
 * \`text()\` and \`amount()\` in display order, pick a color, then \`finish()\`.
 */
export class Result {
  private valueJson: string = "";
  private subParts: string[] = [];
  private sentiment: string = "";

  /** Main figure of the card. */
  value(amount: f64, format: Format, sign: Sign = Sign.Auto): Result {
    this.valueJson = amountJson(amount, format, sign);
    return this;
  }

  /** Literal text in the sub-line. */
  text(text: string): Result {
    this.subParts.push('{"text":' + jsonString(text) + "}");
    return this;
  }

  /** Formatted number in the sub-line. */
  amount(amount: f64, format: Format, sign: Sign = Sign.Auto): Result {
    this.subParts.push(amountJson(amount, format, sign));
    return this;
  }

  /** Color the value by the sign of the main figure. */
  auto(): Result { this.sentiment = "auto"; return this; }
  positive(): Result { this.sentiment = "positive"; return this; }
  negative(): Result { this.sentiment = "negative"; return this; }
  /** Muted color, for costs and informational figures. */
  neutral(): Result { this.sentiment = "neutral"; return this; }

  toJSON(): string {
    if (this.valueJson.length == 0) throw new Error("Result.value() was not called");
    let json = '{"value":' + this.valueJson;
    if (this.subParts.length > 0) json += ',"sub":[' + this.subParts.join(",") + "]";
    if (this.sentiment.length > 0) json += ',"sentiment":"' + this.sentiment + '"';
    return json + "}";
  }

  /** Encode the document and return the pointer the host expects: [u32 length][utf8 bytes]. */
  finish(): i32 {
    return emit(this.toJSON());
  }
}

/** Return any string to the host in the ABI result layout. */
export function emit(json: string): i32 {
  const buf = String.UTF8.encode(json);
  const n = <usize>buf.byteLength;
  const out = heap.alloc(4 + n);
  store<u32>(out, <u32>n);
  memory.copy(out + 4, changetype<usize>(buf), n);
  return <i32>out;
}
`;
}

// ── Repository and manifests ─────────────────────────────────────────────────

function readYaml(path: string): unknown {
  return Bun.YAML.parse(readFileSync(path, "utf8"));
}

function readRepository(): RepositoryEntry[] {
  const raw = readYaml(join(METRICS_DIR, "repository.yml")) as Record<string, unknown>;
  if (!raw || raw["schema"] !== 1 || !Array.isArray(raw["metrics"])) {
    throw new Error("repository.yml must have schema: 1 and a metrics list");
  }
  const seen = new Set<string>();
  return (raw["metrics"] as unknown[]).map((item, index) => {
    const entry = item as Record<string, unknown>;
    if (!isMetricId(entry["id"])) throw new Error(`repository.yml metrics[${index}].id is not a valid metric id`);
    if (seen.has(entry["id"])) throw new Error(`repository.yml lists ${entry["id"]} twice`);
    seen.add(entry["id"]);
    const path = typeof entry["path"] === "string" && entry["path"] ? entry["path"] : entry["id"];
    if (path.includes("..") || path.includes("/")) throw new Error(`repository.yml metrics[${index}].path must be a directory name`);
    return { id: entry["id"], path, bundled: entry["bundled"] !== false };
  });
}

function readManifest(dir: string, expectedId: string): MetricManifest {
  const path = join(dir, "manifest.yml");
  if (!existsSync(path)) throw new Error(`${relative(ROOT, path)} is missing`);
  let manifest: MetricManifest;
  try {
    manifest = validateMetricManifest(readYaml(path));
  } catch (err) {
    throw new Error(`${relative(ROOT, path)}: ${err instanceof Error ? err.message : String(err)}`);
  }
  if (manifest.id !== expectedId) throw new Error(`${relative(ROOT, path)}: id ${manifest.id} does not match repository entry ${expectedId}`);
  if (!manifest.source) throw new Error(`${relative(ROOT, path)}: repository metrics need a source.entry`);
  if (manifest.module) throw new Error(`${relative(ROOT, path)}: repository metrics must not declare module`);
  if (manifest.runtime.memoryPages > MAX_METRIC_MEMORY_PAGES) {
    throw new Error(`${relative(ROOT, path)}: runtime.memoryPages may not exceed ${MAX_METRIC_MEMORY_PAGES}`);
  }
  return manifest;
}

// ── Compilation ──────────────────────────────────────────────────────────────

function newestMtime(paths: string[]): number {
  return Math.max(...paths.map((p) => (existsSync(p) ? statSync(p).mtimeMs : 0)));
}

function listSources(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listSources(full));
    else if (entry.name.endsWith(".ts")) out.push(full);
  }
  return out;
}

async function compile(entry: string, outFile: string, manifest: MetricManifest): Promise<void> {
  mkdirSync(dirname(outFile), { recursive: true });
  const { error, stderr } = await asc.main([
    entry,
    "--outFile",
    outFile,
    "--runtime",
    "stub",
    "--optimize",
    "--noAssert",
    "--importMemory",
    "--noExportMemory",
    "--initialMemory",
    String(MIN_METRIC_MEMORY_PAGES),
    "--maximumMemory",
    String(Math.min(manifest.runtime.memoryPages, MAX_METRIC_MEMORY_PAGES)),
    "--disable",
    "bulk-memory,threads,simd,reference-types",
  ]);
  if (error) {
    throw new Error(`asc failed for ${manifest.id}:\n${stderr.toString()}`);
  }
}

function sha256Hex(bytes: Uint8Array): string {
  return new Bun.CryptoHasher("sha256").update(bytes).digest("hex");
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const sdk = generateSdk();
  const existingSdk = existsSync(SDK_PATH) ? readFileSync(SDK_PATH, "utf8") : "";
  if (existingSdk !== sdk) {
    if (checkOnly) throw new Error(`${relative(ROOT, SDK_PATH)} is stale; run bun run build:metrics and commit it`);
    mkdirSync(dirname(SDK_PATH), { recursive: true });
    writeFileSync(SDK_PATH, sdk);
    console.log(`generated ${relative(ROOT, SDK_PATH)}`);
  }

  const repository = readRepository();
  const bundled: { manifest: MetricManifest; bytes: Uint8Array; sha256: string }[] = [];
  const abiFile = join(ROOT, "src", "shared", "metric-abi.ts");

  for (const entry of repository) {
    const dir = join(METRICS_DIR, entry.path);
    const manifest = readManifest(dir, entry.id);
    const entryFile = resolve(dir, manifest.source!.entry);
    if (!entryFile.startsWith(dir + "/")) throw new Error(`${entry.id}: source.entry must stay inside the metric directory`);
    if (!existsSync(entryFile)) throw new Error(`${entry.id}: ${relative(ROOT, entryFile)} is missing`);

    const outFile = join(OUT_DIR, `${entry.id}.wasm`);
    const inputs = [...listSources(dir), join(dir, "manifest.yml"), SDK_PATH, abiFile, __filename];
    const stale = force || !existsSync(outFile) || statSync(outFile).mtimeMs < newestMtime(inputs);
    if (stale) {
      const started = performance.now();
      await compile(entryFile, outFile, manifest);
      console.log(`compiled ${entry.id} (${Math.round(performance.now() - started)} ms)`);
    }

    const bytes = new Uint8Array(readFileSync(outFile));
    const sha256 = sha256Hex(bytes);
    console.log(`${entry.id.padEnd(24)} ${String(bytes.length).padStart(6)} bytes  sha256 ${sha256.slice(0, 16)}...  v${manifest.version}`);
    if (entry.bundled) bundled.push({ manifest, bytes, sha256 });
  }

  // The starter must always compile, or the first thing a contributor copies is broken.
  const templateDir = join(METRICS_DIR, "_template");
  const templateManifest = validateMetricManifest(readYaml(join(templateDir, "manifest.yml")));
  const templateOut = join(OUT_DIR, "_template.wasm");
  const templateInputs = [...listSources(templateDir), join(templateDir, "manifest.yml"), SDK_PATH, abiFile, __filename];
  if (force || !existsSync(templateOut) || statSync(templateOut).mtimeMs < newestMtime(templateInputs)) {
    await compile(resolve(templateDir, templateManifest.source!.entry), templateOut, templateManifest);
    console.log("compiled _template");
  }

  if (checkOnly) {
    console.log(`checked ${repository.length} metric(s) and the template`);
    return;
  }

  const lines: string[] = [];
  lines.push("// GENERATED by scripts/build-metrics.ts. Do not edit; not committed.");
  lines.push('import type { MetricManifest } from "../../../shared/metric-manifest.js";');
  lines.push("");
  lines.push("export interface BuiltinMetricModule {");
  lines.push("  manifest: MetricManifest;");
  lines.push("  sha256: string;");
  lines.push("  size: number;");
  lines.push("  base64: string;");
  lines.push("}");
  lines.push("");
  lines.push("export interface MetricRepositoryEntry {");
  lines.push("  id: string;");
  lines.push("  bundled: boolean;");
  lines.push("  manifest: MetricManifest;");
  lines.push("}");
  lines.push("");
  lines.push("export const BUILTIN_METRIC_MODULES: readonly BuiltinMetricModule[] = [");
  for (const item of bundled) {
    lines.push("  {");
    lines.push(`    manifest: ${JSON.stringify(item.manifest)},`);
    lines.push(`    sha256: ${JSON.stringify(item.sha256)},`);
    lines.push(`    size: ${item.bytes.length},`);
    lines.push(`    base64: ${JSON.stringify(Buffer.from(item.bytes).toString("base64"))},`);
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");
  lines.push("export const METRIC_REPOSITORY: readonly MetricRepositoryEntry[] = [");
  for (const entry of repository) {
    const manifest = readManifest(join(METRICS_DIR, entry.path), entry.id);
    lines.push(`  { id: ${JSON.stringify(entry.id)}, bundled: ${entry.bundled}, manifest: ${JSON.stringify(manifest)} },`);
  }
  lines.push("];");
  lines.push("");

  mkdirSync(dirname(GENERATED_PATH), { recursive: true });
  const generated = lines.join("\n");
  if (!existsSync(GENERATED_PATH) || readFileSync(GENERATED_PATH, "utf8") !== generated) {
    writeFileSync(GENERATED_PATH, generated);
  }
  const total = bundled.reduce((sum, item) => sum + item.bytes.length, 0);
  console.log(`bundled ${bundled.length} module(s), ${total} bytes -> ${relative(ROOT, GENERATED_PATH)}`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
